[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
priority-queue = "2.1.1"
regex = "1.11.1"

[lib]
name = "core"
path = "src/core/lib.rs"

[[bin]]
name = "puzzle01"
path = "src/puzzle01/main.rs"
